meta_product_name: "Croker"
meta_title: "Croker - Crytocurrency trading for veterans and newbies alike"
meta_description: "Crytocurrency trading for veterans and newbies alike"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@nickpetzold"   # required for Twitter Cards
